dist: xenial
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy2.7-6.0
  - pypy3.5

env:
  global:
    - EXECUTING_SLOW_TESTS=1
    - COVERALLS_PARALLEL=true

before_install:
  - pip install --upgrade coveralls asttokens pytest setuptools setuptools_scm pep517

install:
  - pip install .

script:
  - coverage run --include=executing/executing.py -m unittest tests.test_main
  - coverage run --include=executing/executing.py --append -m pytest tests/test_pytest.py
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
  webhooks: https://coveralls.io/webhook
