dist: xenial
language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy2.7-6.0
  - pypy3.5

install:
  - pip install coveralls
script:
  - PYTHONPATH=`pwd` coverage run --include=executing.py tests/tests.py
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
