dist: xenial
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy2.7-6.0
  - pypy3.5

env:
  global:
    - EXECUTING_SLOW_TESTS=1
    - COVERALLS_PARALLEL=true

before_install:
  - pip install --upgrade coveralls asttokens pytest setuptools>=44 setuptools_scm>=3.4.3 pep517

install:
  - python3 -m pep517.build -b .
  - ls -l
  - export WHLNAME=./dist/stack_data-0.CI-py3-none-any.whl
  - mv ./dist/*.whl $WHLNAME
  - pip install --upgrade "$WHLNAME"

script:
  - coverage run --branch --include=executing.py -m pytest --junitxml=./rspec.xml tests/test_main.py tests/test_pytest.py
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
  webhooks: https://coveralls.io/webhook
