name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, '3.10', 3.11-dev, pypy2, pypy-3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python --version
        pip install -U pip
        pip install --upgrade coveralls setuptools setuptools_scm pep517 .[tests]
        pip install .
    - name: Mypy testing
      run: |
        pip install mypy==0.971
        python -m mypy executing
      # fromJson because https://github.community/t/passing-an-array-literal-to-contains-function-causes-syntax-error/17213/3
      if: ${{ !contains(fromJson('["2.7", "pypy2", "pypy3-6"]'), matrix.python-version) }}
      # pypy < 3.8 very doesn't work
      # 2.7 is tested separately in mypy-py2, as we need to run mypy under Python 3.x        
    - name: Test
      env:
        EXECUTING_SLOW_TESTS: 1
      run: |
        coverage run --include=executing/executing.py -m unittest tests.test_main
        coverage run --include=executing/executing.py --append -m pytest tests/test_pytest.py
        coverage report -m
    - name: Coveralls Python
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        parallel: true
        flag-name: test-${{ matrix.python-version }}

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true

  # Can't run mypy on Python 2.7, but can run it in Python 2 mode
  mypy-py2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade setuptools setuptools_scm pep517
          pip install .[test]
          pip install mypy[python2]==0.971
      - name: Mypy testing for Python 2
        run: |
          python -m mypy --py2 executing