name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10-dev, pypy2, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Coveralls Python
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        parallel: true
    - name: Install dependencies
      run: |
        python --version
        pip install -U pip
        pip install --upgrade coveralls asttokens pytest setuptools setuptools_scm pep517
        pip install .
    - name: Test
      run: |
        coverage run --include=executing/executing.py -m unittest tests.test_main
        coverage run --include=executing/executing.py --append -m pytest tests/test_pytest.py
        coverage report -m

  coveralls_finish:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
